[1.20] Update texture encoding
Asek3/Oculus pull request #519
Opened 2023-12-22 00:53 UTC by embeddedt

The next version of Embeddium will make a backwards-incompatible change to how textures are encoded to address visual alignment issues (this change will also be made in Sodium whenever the next release occurs). It will require an Oculus update for shaders to function correctly again.

2023-12-22 06:12 UTC, dima-dencep requested changes
Change minimal version of embeddium in mods.toml

2023-12-24 17:12 UTC, embeddedt commented
Minimum version has been set to 0.2.14.

2023-12-24 17:15 UTC, dima-dencep commented
Oculus can work without embeddium, and I don't want it to be dependent on it (there have been cases where people only needed oculus without embeddium)

2023-12-24 17:16 UTC, embeddedt commented
It will perform incredibly poorly due to the massive vertex size... but sure.

2023-12-24 17:17 UTC, dima-dencep approved these changes

2023-12-24 17:18 UTC, merged