Mekasuit render fix backport. fixes https://github.com/Asek3/Oculus/i…
Asek3/Oculus pull request #701
Opened 2024-10-03 02:06 UTC by KostromDan

…ssues/170

2024-10-03 02:08 UTC, KostromDan commented
![image](https://github.com/user-attachments/assets/f017013f-9bcc-4412-bc31-2fbd2f6f99a1)

2024-10-05 07:09 UTC, dima-dencep requested changes

2024-10-05 07:09 UTC, dima-dencep commented on src/main/java/net/coderbot/iris/pipeline/newshader/ShaderKey.java
> +
Revert

2024-10-09 09:58 UTC, dima-dencep commented on src/main/java/net/coderbot/iris/pipeline/newshader/ShaderKey.java
> +
Oops, I accidentally highlighted an extra line (the last one with `MEKANISM_FLAME_SHADOW`), it doesn't need to be rolled back

2024-10-18 07:51 UTC, KostromDan commented
Noticed differences in tab length between GitHub and my IDE. If it looked correct in the IDE, it looked wrong on GitHub. When I fixed it in the GitHub editor and copied it back to the IDE, it started looking incorrect there. So, I replaced tabs with spaces, and now it looks correct in both places.

2024-10-18 08:05 UTC, dima-dencep requested changes
I hate to break it to you, but you made even more unnecessary changes

2024-10-18 08:23 UTC, dima-dencep commented
> Noticed differences in tab length between GitHub and IDEs

skill issue

2024-10-18 08:27 UTC, KostromDan commented
> > Noticed differences in tab length between GitHub and IDEs
> 
> skill issue

https://github.com/Asek3/Oculus/blob/1.19.2/src/main/java/net/coderbot/iris/pipeline/newshader/ShaderKey.java#L63
Wdym, is it correct? In IntelliJ IDEA or VS Code it looks correct, but not on GitHub.
How it looks on GitHub:
![image](https://github.com/user-attachments/assets/a77bc847-67cc-4ecd-86c1-aafd8f90de85)
How it looks in IDE(tabs are highlited):
![image](https://github.com/user-attachments/assets/9676b3f1-cf59-4df4-9ded-d75618445de4)

2024-10-18 08:29 UTC, KostromDan commented
If you want I'll revert my fixes and apply only requested, but I think it should look correct on both IDEs and GitHub.

2024-10-18 08:30 UTC, dima-dencep commented
I don't care how it looks to you, you can see how it looks to everyone in your own pr and I don't understand why you don't see these changes in diff

2024-10-18 08:40 UTC, dima-dencep approved these changes

2024-10-18 08:40 UTC, merged