Upgrade support for Distant Horizons 2.2
Asek3/Oculus pull request #702
Opened 2024-10-05 15:55 UTC by IMS212

2024-10-05 17:59 UTC, dima-dencep requested changes

2024-10-05 17:59 UTC, dima-dencep commented on src/main/java/net/irisshaders/iris/mixin/MixinLevelRenderer.java
>  import org.spongepowered.asm.mixin.injection.*;
Revert

2024-10-05 17:59 UTC, dima-dencep commented on src/main/java/net/irisshaders/iris/compat/dh/DHMixinConfigPlugin.java
> +}
Such a config plugin already exists

2024-10-05 17:59 UTC, dima-dencep commented on build.gradle
> +	modCompileOnly("maven.modrinth:distanthorizonsapi:3.0.0")
Maybe the file itself should be deleted too?

2024-10-05 21:09 UTC, IMS212 commented
done

2024-10-06 02:42 UTC, dima-dencep approved these changes

2024-10-06 02:43 UTC, merged

2024-10-30 11:04 UTC, mpustovoi commented
Any further progress here?